# Generated by Django 5.2.9 on 2026-01-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Modern', 'Modern'), ('Classic', 'Classic')], default='Modern', max_length=30)),
                ('layout', models.CharField(choices=[('Two Column', 'Two Column'), ('Single Column', 'Single Column'), ('Sidebar Left', 'Sidebar Left'), ('Sidebar Right', 'Sidebar Right')], default='Two Column', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('color', models.CharField(default='#2563eb', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('free', 'Free'), ('one_time', 'One-time'), ('subscription', 'Subscription')], default='one_time', max_length=20)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3)),
                ('price', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='users.resumetemplate')),
            ],
        ),
    ]
