# Generated by Django 5.2.9 on 2026-01-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resumetemplate_templatepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Pro', 'Pro'), ('Enterprise', 'Enterprise')], max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Past Due', 'Past Due')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
