# Generated by Django 5.2.9 on 2026-01-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='templates/previews/'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='source',
            field=models.CharField(choices=[('custom', 'Custom'), ('imported', 'Imported'), ('duplicated', 'Duplicated')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
