# Generated by Django 5.2.9 on 2026-01-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resumedocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeDocument',
        ),
    ]
